//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DryadUnity {

public class EdgeVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Edge>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EdgeVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EdgeVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EdgeVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadApiPINVOKE.delete_EdgeVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EdgeVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Edge element in c) {
      this.Add(element);
    }
  }

  public EdgeVector(global::System.Collections.Generic.IEnumerable<Edge> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Edge element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Edge this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Edge[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Edge[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Edge[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Edge[] ToArray() {
    Edge[] array = new Edge[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Edge> global::System.Collections.Generic.IEnumerable<Edge>.GetEnumerator() {
    return new EdgeVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new EdgeVectorEnumerator(this);
  }

  public EdgeVectorEnumerator GetEnumerator() {
    return new EdgeVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class EdgeVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Edge>
  {
    private EdgeVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public EdgeVectorEnumerator(EdgeVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Edge Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Edge)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    DryadApiPINVOKE.EdgeVector_Clear(swigCPtr);
  }

  public void Add(Edge x) {
    DryadApiPINVOKE.EdgeVector_Add(swigCPtr, Edge.getCPtr(x));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = DryadApiPINVOKE.EdgeVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = DryadApiPINVOKE.EdgeVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    DryadApiPINVOKE.EdgeVector_reserve(swigCPtr, n);
  }

  public EdgeVector() : this(DryadApiPINVOKE.new_EdgeVector__SWIG_0(), true) {
  }

  public EdgeVector(EdgeVector other) : this(DryadApiPINVOKE.new_EdgeVector__SWIG_1(EdgeVector.getCPtr(other)), true) {
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public EdgeVector(int capacity) : this(DryadApiPINVOKE.new_EdgeVector__SWIG_2(capacity), true) {
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  private Edge getitemcopy(int index) {
    Edge ret = new Edge(DryadApiPINVOKE.EdgeVector_getitemcopy(swigCPtr, index), true);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Edge getitem(int index) {
    Edge ret = new Edge(DryadApiPINVOKE.EdgeVector_getitem(swigCPtr, index), false);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Edge val) {
    DryadApiPINVOKE.EdgeVector_setitem(swigCPtr, index, Edge.getCPtr(val));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(EdgeVector values) {
    DryadApiPINVOKE.EdgeVector_AddRange(swigCPtr, EdgeVector.getCPtr(values));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public EdgeVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = DryadApiPINVOKE.EdgeVector_GetRange(swigCPtr, index, count);
    EdgeVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new EdgeVector(cPtr, true);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Edge x) {
    DryadApiPINVOKE.EdgeVector_Insert(swigCPtr, index, Edge.getCPtr(x));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, EdgeVector values) {
    DryadApiPINVOKE.EdgeVector_InsertRange(swigCPtr, index, EdgeVector.getCPtr(values));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    DryadApiPINVOKE.EdgeVector_RemoveAt(swigCPtr, index);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    DryadApiPINVOKE.EdgeVector_RemoveRange(swigCPtr, index, count);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public static EdgeVector Repeat(Edge value, int count) {
    global::System.IntPtr cPtr = DryadApiPINVOKE.EdgeVector_Repeat(Edge.getCPtr(value), count);
    EdgeVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new EdgeVector(cPtr, true);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    DryadApiPINVOKE.EdgeVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    DryadApiPINVOKE.EdgeVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, EdgeVector values) {
    DryadApiPINVOKE.EdgeVector_SetRange(swigCPtr, index, EdgeVector.getCPtr(values));
    if (DryadApiPINVOKE.SWIGPendingException.Pending) throw DryadApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
