//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DryadUnity {

public class Event : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Event(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Event obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Event() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadApiPINVOKE.delete_Event(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EventFlag flag {
    set {
      DryadApiPINVOKE.Event_flag_set(swigCPtr, (int)value);
    } 
    get {
      EventFlag ret = (EventFlag)DryadApiPINVOKE.Event_flag_get(swigCPtr);
      return ret;
    } 
  }

  public int id {
    set {
      DryadApiPINVOKE.Event_id_set(swigCPtr, value);
    } 
    get {
      int ret = DryadApiPINVOKE.Event_id_get(swigCPtr);
      return ret;
    } 
  }

  public double time {
    set {
      DryadApiPINVOKE.Event_time_set(swigCPtr, value);
    } 
    get {
      double ret = DryadApiPINVOKE.Event_time_get(swigCPtr);
      return ret;
    } 
  }

  public NoteConcreteVector notes {
    set {
      DryadApiPINVOKE.Event_notes_set(swigCPtr, NoteConcreteVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DryadApiPINVOKE.Event_notes_get(swigCPtr);
      NoteConcreteVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new NoteConcreteVector(cPtr, false);
      return ret;
    } 
  }

  public Event() : this(DryadApiPINVOKE.new_Event(), true) {
  }

}

}
