//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DryadUnity {

public class NoteConcept : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NoteConcept(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NoteConcept obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NoteConcept() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadApiPINVOKE.delete_NoteConcept(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int duration {
    set {
      DryadApiPINVOKE.NoteConcept_duration_set(swigCPtr, value);
    } 
    get {
      int ret = DryadApiPINVOKE.NoteConcept_duration_get(swigCPtr);
      return ret;
    } 
  }

  public int value {
    set {
      DryadApiPINVOKE.NoteConcept_value_set(swigCPtr, value);
    } 
    get {
      int ret = DryadApiPINVOKE.NoteConcept_value_get(swigCPtr);
      return ret;
    } 
  }

  public NoteConcept() : this(DryadApiPINVOKE.new_NoteConcept(), true) {
  }

}

}
