//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

public class LandscapeGraph : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LandscapeGraph(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LandscapeGraph obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LandscapeGraph() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadFacadePINVOKE.delete_LandscapeGraph(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint id {
    set {
      DryadFacadePINVOKE.LandscapeGraph_id_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.LandscapeGraph_id_get(swigCPtr);
      return ret;
    } 
  }

  public Scale scale {
    set {
      DryadFacadePINVOKE.LandscapeGraph_scale_set(swigCPtr, Scale.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DryadFacadePINVOKE.LandscapeGraph_scale_get(swigCPtr);
      Scale ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scale(cPtr, false);
      return ret;
    } 
  }

  public string name {
    set {
      DryadFacadePINVOKE.LandscapeGraph_name_set(swigCPtr, value);
      if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = DryadFacadePINVOKE.LandscapeGraph_name_get(swigCPtr);
      if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NodeList nodes {
    set {
      DryadFacadePINVOKE.LandscapeGraph_nodes_set(swigCPtr, NodeList.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DryadFacadePINVOKE.LandscapeGraph_nodes_get(swigCPtr);
      NodeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodeList(cPtr, false);
      return ret;
    } 
  }

  public EdgeList edges {
    set {
      DryadFacadePINVOKE.LandscapeGraph_edges_set(swigCPtr, EdgeList.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DryadFacadePINVOKE.LandscapeGraph_edges_get(swigCPtr);
      EdgeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new EdgeList(cPtr, false);
      return ret;
    } 
  }

  public LandscapeGraph() : this(DryadFacadePINVOKE.new_LandscapeGraph(), true) {
  }

}

}
