//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

public class MotifNote : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MotifNote(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MotifNote obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MotifNote() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadFacadePINVOKE.delete_MotifNote(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint scoreTime {
    set {
      DryadFacadePINVOKE.MotifNote_scoreTime_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.MotifNote_scoreTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint duration {
    set {
      DryadFacadePINVOKE.MotifNote_duration_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.MotifNote_duration_get(swigCPtr);
      return ret;
    } 
  }

  public int offset {
    set {
      DryadFacadePINVOKE.MotifNote_offset_set(swigCPtr, value);
    } 
    get {
      int ret = DryadFacadePINVOKE.MotifNote_offset_get(swigCPtr);
      return ret;
    } 
  }

  public MotifNote() : this(DryadFacadePINVOKE.new_MotifNote(), true) {
  }

}

}
