//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

public class Motif : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Motif(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Motif obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Motif() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadFacadePINVOKE.delete_Motif(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint id {
    set {
      DryadFacadePINVOKE.Motif_id_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.Motif_id_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      DryadFacadePINVOKE.Motif_name_set(swigCPtr, value);
      if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = DryadFacadePINVOKE.Motif_name_get(swigCPtr);
      if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint duration {
    set {
      DryadFacadePINVOKE.Motif_duration_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.Motif_duration_get(swigCPtr);
      return ret;
    } 
  }

  public MotifList notes {
    set {
      DryadFacadePINVOKE.Motif_notes_set(swigCPtr, MotifList.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DryadFacadePINVOKE.Motif_notes_get(swigCPtr);
      MotifList ret = (cPtr == global::System.IntPtr.Zero) ? null : new MotifList(cPtr, false);
      return ret;
    } 
  }

  public Motif() : this(DryadFacadePINVOKE.new_Motif(), true) {
  }

}

}
