//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

public class NodeList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Node>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NodeList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NodeList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NodeList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadFacadePINVOKE.delete_NodeList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public NodeList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Node element in c) {
      this.Add(element);
    }
  }

  public NodeList(global::System.Collections.Generic.IEnumerable<Node> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Node element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Node this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Node[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Node[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Node[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Node[] ToArray() {
    Node[] array = new Node[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Node> global::System.Collections.Generic.IEnumerable<Node>.GetEnumerator() {
    return new NodeListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new NodeListEnumerator(this);
  }

  public NodeListEnumerator GetEnumerator() {
    return new NodeListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class NodeListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Node>
  {
    private NodeList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public NodeListEnumerator(NodeList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Node Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Node)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    DryadFacadePINVOKE.NodeList_Clear(swigCPtr);
  }

  public void Add(Node x) {
    DryadFacadePINVOKE.NodeList_Add(swigCPtr, Node.getCPtr(x));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = DryadFacadePINVOKE.NodeList_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = DryadFacadePINVOKE.NodeList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    DryadFacadePINVOKE.NodeList_reserve(swigCPtr, n);
  }

  public NodeList() : this(DryadFacadePINVOKE.new_NodeList__SWIG_0(), true) {
  }

  public NodeList(NodeList other) : this(DryadFacadePINVOKE.new_NodeList__SWIG_1(NodeList.getCPtr(other)), true) {
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public NodeList(int capacity) : this(DryadFacadePINVOKE.new_NodeList__SWIG_2(capacity), true) {
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  private Node getitemcopy(int index) {
    Node ret = new Node(DryadFacadePINVOKE.NodeList_getitemcopy(swigCPtr, index), true);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Node getitem(int index) {
    Node ret = new Node(DryadFacadePINVOKE.NodeList_getitem(swigCPtr, index), false);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Node val) {
    DryadFacadePINVOKE.NodeList_setitem(swigCPtr, index, Node.getCPtr(val));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(NodeList values) {
    DryadFacadePINVOKE.NodeList_AddRange(swigCPtr, NodeList.getCPtr(values));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public NodeList GetRange(int index, int count) {
    global::System.IntPtr cPtr = DryadFacadePINVOKE.NodeList_GetRange(swigCPtr, index, count);
    NodeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodeList(cPtr, true);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Node x) {
    DryadFacadePINVOKE.NodeList_Insert(swigCPtr, index, Node.getCPtr(x));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, NodeList values) {
    DryadFacadePINVOKE.NodeList_InsertRange(swigCPtr, index, NodeList.getCPtr(values));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    DryadFacadePINVOKE.NodeList_RemoveAt(swigCPtr, index);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    DryadFacadePINVOKE.NodeList_RemoveRange(swigCPtr, index, count);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public static NodeList Repeat(Node value, int count) {
    global::System.IntPtr cPtr = DryadFacadePINVOKE.NodeList_Repeat(Node.getCPtr(value), count);
    NodeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodeList(cPtr, true);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    DryadFacadePINVOKE.NodeList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    DryadFacadePINVOKE.NodeList_Reverse__SWIG_1(swigCPtr, index, count);
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, NodeList values) {
    DryadFacadePINVOKE.NodeList_SetRange(swigCPtr, index, NodeList.getCPtr(values));
    if (DryadFacadePINVOKE.SWIGPendingException.Pending) throw DryadFacadePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
