//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

public class Node : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Node(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Node obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Node() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DryadFacadePINVOKE.delete_Node(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint id {
    set {
      DryadFacadePINVOKE.Node_id_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.Node_id_get(swigCPtr);
      return ret;
    } 
  }

  public uint degree {
    set {
      DryadFacadePINVOKE.Node_degree_set(swigCPtr, value);
    } 
    get {
      uint ret = DryadFacadePINVOKE.Node_degree_get(swigCPtr);
      return ret;
    } 
  }

  public int inversion {
    set {
      DryadFacadePINVOKE.Node_inversion_set(swigCPtr, value);
    } 
    get {
      int ret = DryadFacadePINVOKE.Node_inversion_get(swigCPtr);
      return ret;
    } 
  }

  public int accidental {
    set {
      DryadFacadePINVOKE.Node_accidental_set(swigCPtr, value);
    } 
    get {
      int ret = DryadFacadePINVOKE.Node_accidental_get(swigCPtr);
      return ret;
    } 
  }

  public int shift {
    set {
      DryadFacadePINVOKE.Node_shift_set(swigCPtr, value);
    } 
    get {
      int ret = DryadFacadePINVOKE.Node_shift_get(swigCPtr);
      return ret;
    } 
  }

  public bool entry {
    set {
      DryadFacadePINVOKE.Node_entry_set(swigCPtr, value);
    } 
    get {
      bool ret = DryadFacadePINVOKE.Node_entry_get(swigCPtr);
      return ret;
    } 
  }

  public TriadVoicing triadVoicing {
    set {
      DryadFacadePINVOKE.Node_triadVoicing_set(swigCPtr, (int)value);
    } 
    get {
      TriadVoicing ret = (TriadVoicing)DryadFacadePINVOKE.Node_triadVoicing_get(swigCPtr);
      return ret;
    } 
  }

  public ChordExtension chordExtension {
    set {
      DryadFacadePINVOKE.Node_chordExtension_set(swigCPtr, (int)value);
    } 
    get {
      ChordExtension ret = (ChordExtension)DryadFacadePINVOKE.Node_chordExtension_get(swigCPtr);
      return ret;
    } 
  }

  public Node() : this(DryadFacadePINVOKE.new_Node(), true) {
  }

}

}
