//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Dryad {

class DryadFacadePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="SWIGRegisterExceptionCallbacks_DryadFacade")]
    public static extern void SWIGRegisterExceptionCallbacks_DryadFacade(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_DryadFacade")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_DryadFacade(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_DryadFacade(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_DryadFacade(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="SWIGRegisterStringCallback_DryadFacade")]
    public static extern void SWIGRegisterStringCallback_DryadFacade(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_DryadFacade(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static DryadFacadePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_scoreTime_set")]
  public static extern void NoteToPlay_scoreTime_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_scoreTime_get")]
  public static extern uint NoteToPlay_scoreTime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_midiValue_set")]
  public static extern void NoteToPlay_midiValue_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_midiValue_get")]
  public static extern uint NoteToPlay_midiValue_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_duration_set")]
  public static extern void NoteToPlay_duration_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_duration_get")]
  public static extern uint NoteToPlay_duration_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_parentMotif_set")]
  public static extern void NoteToPlay_parentMotif_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlay_parentMotif_get")]
  public static extern uint NoteToPlay_parentMotif_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NoteToPlay")]
  public static extern global::System.IntPtr new_NoteToPlay();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_NoteToPlay")]
  public static extern void delete_NoteToPlay(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_scoreTime_set")]
  public static extern void MotifNote_scoreTime_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_scoreTime_get")]
  public static extern uint MotifNote_scoreTime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_duration_set")]
  public static extern void MotifNote_duration_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_duration_get")]
  public static extern uint MotifNote_duration_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_offset_set")]
  public static extern void MotifNote_offset_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifNote_offset_get")]
  public static extern int MotifNote_offset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_MotifNote")]
  public static extern global::System.IntPtr new_MotifNote();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_MotifNote")]
  public static extern void delete_MotifNote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_id_set")]
  public static extern void Motif_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_id_get")]
  public static extern uint Motif_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_name_set")]
  public static extern void Motif_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_name_get")]
  public static extern string Motif_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_duration_set")]
  public static extern void Motif_duration_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_duration_get")]
  public static extern uint Motif_duration_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_notes_set")]
  public static extern void Motif_notes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Motif_notes_get")]
  public static extern global::System.IntPtr Motif_notes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_Motif")]
  public static extern global::System.IntPtr new_Motif();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_Motif")]
  public static extern void delete_Motif(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_name_set")]
  public static extern void Scale_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_name_get")]
  public static extern string Scale_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_rootNote_set")]
  public static extern void Scale_rootNote_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_rootNote_get")]
  public static extern uint Scale_rootNote_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_flatOrSharp_set")]
  public static extern void Scale_flatOrSharp_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_flatOrSharp_get")]
  public static extern int Scale_flatOrSharp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_intervals_set")]
  public static extern void Scale_intervals_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Scale_intervals_get")]
  public static extern global::System.IntPtr Scale_intervals_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_Scale")]
  public static extern global::System.IntPtr new_Scale();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_Scale")]
  public static extern void delete_Scale(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_id_set")]
  public static extern void Node_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_id_get")]
  public static extern uint Node_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_degree_set")]
  public static extern void Node_degree_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_degree_get")]
  public static extern uint Node_degree_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_inversion_set")]
  public static extern void Node_inversion_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_inversion_get")]
  public static extern int Node_inversion_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_accidental_set")]
  public static extern void Node_accidental_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_accidental_get")]
  public static extern int Node_accidental_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_shift_set")]
  public static extern void Node_shift_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_shift_get")]
  public static extern int Node_shift_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_entry_set")]
  public static extern void Node_entry_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_entry_get")]
  public static extern bool Node_entry_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_triadVoicing_set")]
  public static extern void Node_triadVoicing_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_triadVoicing_get")]
  public static extern int Node_triadVoicing_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_chordExtension_set")]
  public static extern void Node_chordExtension_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Node_chordExtension_get")]
  public static extern int Node_chordExtension_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_Node")]
  public static extern global::System.IntPtr new_Node();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_Node")]
  public static extern void delete_Node(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Edge_from_set")]
  public static extern void Edge_from_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Edge_from_get")]
  public static extern uint Edge_from_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Edge_to_set")]
  public static extern void Edge_to_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Edge_to_get")]
  public static extern uint Edge_to_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_Edge")]
  public static extern global::System.IntPtr new_Edge();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_Edge")]
  public static extern void delete_Edge(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_id_set")]
  public static extern void LandscapeGraph_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_id_get")]
  public static extern uint LandscapeGraph_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_scale_set")]
  public static extern void LandscapeGraph_scale_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_scale_get")]
  public static extern global::System.IntPtr LandscapeGraph_scale_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_name_set")]
  public static extern void LandscapeGraph_name_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_name_get")]
  public static extern string LandscapeGraph_name_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_nodes_set")]
  public static extern void LandscapeGraph_nodes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_nodes_get")]
  public static extern global::System.IntPtr LandscapeGraph_nodes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_edges_set")]
  public static extern void LandscapeGraph_edges_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_LandscapeGraph_edges_get")]
  public static extern global::System.IntPtr LandscapeGraph_edges_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_LandscapeGraph")]
  public static extern global::System.IntPtr new_LandscapeGraph();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_LandscapeGraph")]
  public static extern void delete_LandscapeGraph(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_Facade")]
  public static extern global::System.IntPtr new_Facade();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_Facade")]
  public static extern void delete_Facade(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_RegisterMotif")]
  public static extern void Facade_RegisterMotif(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_RegisterLandscape")]
  public static extern void Facade_RegisterLandscape(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_AddMotif")]
  public static extern void Facade_AddMotif(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_RemoveMotif")]
  public static extern void Facade_RemoveMotif(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_SetLandscape")]
  public static extern void Facade_SetLandscape(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_Generate")]
  public static extern void Facade_Generate(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_Facade_Play")]
  public static extern global::System.IntPtr Facade_Play(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Clear")]
  public static extern void MotifList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Add")]
  public static extern void MotifList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_size")]
  public static extern uint MotifList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_capacity")]
  public static extern uint MotifList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_reserve")]
  public static extern void MotifList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_MotifList__SWIG_0")]
  public static extern global::System.IntPtr new_MotifList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_MotifList__SWIG_1")]
  public static extern global::System.IntPtr new_MotifList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_MotifList__SWIG_2")]
  public static extern global::System.IntPtr new_MotifList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_getitemcopy")]
  public static extern global::System.IntPtr MotifList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_getitem")]
  public static extern global::System.IntPtr MotifList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_setitem")]
  public static extern void MotifList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_AddRange")]
  public static extern void MotifList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_GetRange")]
  public static extern global::System.IntPtr MotifList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Insert")]
  public static extern void MotifList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_InsertRange")]
  public static extern void MotifList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_RemoveAt")]
  public static extern void MotifList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_RemoveRange")]
  public static extern void MotifList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Repeat")]
  public static extern global::System.IntPtr MotifList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Reverse__SWIG_0")]
  public static extern void MotifList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_Reverse__SWIG_1")]
  public static extern void MotifList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_MotifList_SetRange")]
  public static extern void MotifList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_MotifList")]
  public static extern void delete_MotifList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Clear")]
  public static extern void NodeList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Add")]
  public static extern void NodeList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_size")]
  public static extern uint NodeList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_capacity")]
  public static extern uint NodeList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_reserve")]
  public static extern void NodeList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NodeList__SWIG_0")]
  public static extern global::System.IntPtr new_NodeList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NodeList__SWIG_1")]
  public static extern global::System.IntPtr new_NodeList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NodeList__SWIG_2")]
  public static extern global::System.IntPtr new_NodeList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_getitemcopy")]
  public static extern global::System.IntPtr NodeList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_getitem")]
  public static extern global::System.IntPtr NodeList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_setitem")]
  public static extern void NodeList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_AddRange")]
  public static extern void NodeList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_GetRange")]
  public static extern global::System.IntPtr NodeList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Insert")]
  public static extern void NodeList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_InsertRange")]
  public static extern void NodeList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_RemoveAt")]
  public static extern void NodeList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_RemoveRange")]
  public static extern void NodeList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Repeat")]
  public static extern global::System.IntPtr NodeList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Reverse__SWIG_0")]
  public static extern void NodeList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_Reverse__SWIG_1")]
  public static extern void NodeList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NodeList_SetRange")]
  public static extern void NodeList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_NodeList")]
  public static extern void delete_NodeList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Clear")]
  public static extern void EdgeList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Add")]
  public static extern void EdgeList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_size")]
  public static extern uint EdgeList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_capacity")]
  public static extern uint EdgeList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_reserve")]
  public static extern void EdgeList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_EdgeList__SWIG_0")]
  public static extern global::System.IntPtr new_EdgeList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_EdgeList__SWIG_1")]
  public static extern global::System.IntPtr new_EdgeList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_EdgeList__SWIG_2")]
  public static extern global::System.IntPtr new_EdgeList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_getitemcopy")]
  public static extern global::System.IntPtr EdgeList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_getitem")]
  public static extern global::System.IntPtr EdgeList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_setitem")]
  public static extern void EdgeList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_AddRange")]
  public static extern void EdgeList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_GetRange")]
  public static extern global::System.IntPtr EdgeList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Insert")]
  public static extern void EdgeList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_InsertRange")]
  public static extern void EdgeList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_RemoveAt")]
  public static extern void EdgeList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_RemoveRange")]
  public static extern void EdgeList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Repeat")]
  public static extern global::System.IntPtr EdgeList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Reverse__SWIG_0")]
  public static extern void EdgeList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_Reverse__SWIG_1")]
  public static extern void EdgeList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_EdgeList_SetRange")]
  public static extern void EdgeList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_EdgeList")]
  public static extern void delete_EdgeList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Clear")]
  public static extern void IntervalList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Add")]
  public static extern void IntervalList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_size")]
  public static extern uint IntervalList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_capacity")]
  public static extern uint IntervalList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_reserve")]
  public static extern void IntervalList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_IntervalList__SWIG_0")]
  public static extern global::System.IntPtr new_IntervalList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_IntervalList__SWIG_1")]
  public static extern global::System.IntPtr new_IntervalList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_IntervalList__SWIG_2")]
  public static extern global::System.IntPtr new_IntervalList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_getitemcopy")]
  public static extern uint IntervalList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_getitem")]
  public static extern uint IntervalList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_setitem")]
  public static extern void IntervalList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_AddRange")]
  public static extern void IntervalList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_GetRange")]
  public static extern global::System.IntPtr IntervalList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Insert")]
  public static extern void IntervalList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_InsertRange")]
  public static extern void IntervalList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_RemoveAt")]
  public static extern void IntervalList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_RemoveRange")]
  public static extern void IntervalList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Repeat")]
  public static extern global::System.IntPtr IntervalList_Repeat(uint jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Reverse__SWIG_0")]
  public static extern void IntervalList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Reverse__SWIG_1")]
  public static extern void IntervalList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_SetRange")]
  public static extern void IntervalList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Contains")]
  public static extern bool IntervalList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_IndexOf")]
  public static extern int IntervalList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_LastIndexOf")]
  public static extern int IntervalList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_IntervalList_Remove")]
  public static extern bool IntervalList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_IntervalList")]
  public static extern void delete_IntervalList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Clear")]
  public static extern void NoteToPlayList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Add")]
  public static extern void NoteToPlayList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_size")]
  public static extern uint NoteToPlayList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_capacity")]
  public static extern uint NoteToPlayList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_reserve")]
  public static extern void NoteToPlayList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NoteToPlayList__SWIG_0")]
  public static extern global::System.IntPtr new_NoteToPlayList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NoteToPlayList__SWIG_1")]
  public static extern global::System.IntPtr new_NoteToPlayList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_new_NoteToPlayList__SWIG_2")]
  public static extern global::System.IntPtr new_NoteToPlayList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_getitemcopy")]
  public static extern global::System.IntPtr NoteToPlayList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_getitem")]
  public static extern global::System.IntPtr NoteToPlayList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_setitem")]
  public static extern void NoteToPlayList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_AddRange")]
  public static extern void NoteToPlayList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_GetRange")]
  public static extern global::System.IntPtr NoteToPlayList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Insert")]
  public static extern void NoteToPlayList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_InsertRange")]
  public static extern void NoteToPlayList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_RemoveAt")]
  public static extern void NoteToPlayList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_RemoveRange")]
  public static extern void NoteToPlayList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Repeat")]
  public static extern global::System.IntPtr NoteToPlayList_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Reverse__SWIG_0")]
  public static extern void NoteToPlayList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_Reverse__SWIG_1")]
  public static extern void NoteToPlayList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_NoteToPlayList_SetRange")]
  public static extern void NoteToPlayList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("DryadFacade", EntryPoint="CSharp_Dryad_delete_NoteToPlayList")]
  public static extern void delete_NoteToPlayList(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
